//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi4
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemTungMon
    {
        public int STT { get; set; }
        public string MaMonHoc { get; set; }
        public string TenMonHoc { get; set; }
        public string MaHocSinh { get; set; }
        public Nullable<double> DiemHeSoI_HKI { get; set; }
        public Nullable<double> DiemHeSoII_HKI { get; set; }
        public Nullable<double> DiemHeSoIII_HKI { get; set; }
        public Nullable<double> TongKet_HKI { get; set; }
        public Nullable<double> DiemHeSoI_HKII { get; set; }
        public Nullable<double> DiemHeSoII_HKII { get; set; }
        public Nullable<double> DiemHeSoIII_HKII { get; set; }
        public Nullable<double> TongKet_HKII { get; set; }
        public Nullable<double> DiemTrungBinhCaNam { get; set; }
        public Nullable<int> MaNam { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual NamHoc NamHoc { get; set; }
    }
}
