//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi4
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        public string MaGiaoVien { get; set; }
        public string MaLop { get; set; }
        public string NameGV { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string LienHe { get; set; }
        public Nullable<bool> LaGVCN { get; set; }
        public string MaMonHoc { get; set; }
        public string LinkAnh { get; set; }
        public string MatKhau { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
