//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi4
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocSinh()
        {
            this.DiemTungMons = new HashSet<DiemTungMon>();
            this.HanhKiems = new HashSet<HanhKiem>();
            this.ThanhTiches = new HashSet<ThanhTich>();
        }
    
        public string MaHocSinh { get; set; }
        public string MaLop { get; set; }
        public string NameHS { get; set; }
        public string NoiSinh { get; set; }
        public string NoiO { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string LienHe { get; set; }
        public string LinkAnh { get; set; }
        public string MatKhau { get; set; }
    
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemTungMon> DiemTungMons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HanhKiem> HanhKiems { get; set; }
        public virtual PhuHuynh PhuHuynh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhTich> ThanhTiches { get; set; }
    }
}
