//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi4
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuHuynh
    {
        public string MaHocSinh { get; set; }
        public string NamePH { get; set; }
        public string KhuVuc { get; set; }
        public string QuanHeVoiHocSinh { get; set; }
        public string LienHe { get; set; }
        public string NgheNghiep { get; set; }
        public string LinkAnh { get; set; }
        public string MatKhau { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
    }
}
