//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnKi4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhTich
    {
        public int STT { get; set; }
        public string MaHocSinh { get; set; }
        public string XepLoaiCaNam { get; set; }
        public string CacThanhTichKhac { get; set; }
        public Nullable<int> MaNam { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual NamHoc NamHoc { get; set; }
    }
}
